name: Aktualizuj rekomendacje

on:
  schedule:
    - cron: '30 14 * * *'  # codziennie o 16:30 polskiego czasu (14:30 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Klonuj repozytorium
        uses: actions/checkout@v3

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Zainstaluj biblioteki
        run: pip install yfinance

      - name: Uruchom doradcę
        run: python doradca.py

      - name: Commit i push zmian
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add rekomendacje.html
          git commit -m "Aktualizacja rekomendacji $(date +'%d-%m-%Y')" || echo "Brak zmian"
          git push
